name: Build and publish Python SDK wheel to pypi

on:
  release:
    types: [created]

jobs:
  build:
    name: Build distribution ðŸ“¦
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: grpc_sdk/python
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        uses: kaisugi/action-regex-match@v1.0.1
        id: extract-version
        with:
          text: ${{ github.event.ref }}
          regex: ^refs/tags/v([0-9]+\.[0-9]+(\.[0-9]+)?)$

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pypa/build
        run: python3 -mpip install --user build

      - name: Build a binary wheel and a source tarball
        run: python3 -m build
        env:
          VERSION: "${{ github.event.release.tag_name }}"

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: grpc_sdk/python/dist/


  publish-to-pypi:
    name: Publish to pypi.org
    needs: [ build ]
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/gnetclisdk

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verify-metadata: false
